[server]
host=localhost

[midi]
device=nanoPAD

# nanoPAD Layout:
#   Scene 1:
#     39, 48, 45, 43, 51, 49,
#     36, 38, 40, 42, 44, 46
[eventmap]
39=cam3 cam1 pip
48=cam3 cam2 pip
45=cam3 cam1 sbs
43=cam3 cam2 lec
51=cam1 cam2 sbs
36=cam1 * fs
38=cam2 * fs
40=cam3 * fs
