[server]
host=localhost

[midi]
device=nanoPAD

# nanoPAD Layout:
#   Scene 1:
#     39, 48, 45, 43, 51, 49,
#     36, 38, 40, 42, 44, 46
[eventmap]
<<<<<<< HEAD
39=grabber cam1 side_by_side_preview
48=grabber cam2 side_by_side_preview
45=grabber cam1 side_by_side_equal
43=grabber cam2 side_by_side_equal
51=cam1 cam2 side_by_side_equal
36=cam1 * fullscreen
38=cam2 * fullscreen
40=grabber * fullscreen
=======
39=cam3 cam1 pip
48=cam3 cam2 pip
45=cam3 cam1 sbs
43=cam3 cam2 lec
51=cam1 cam2 sbs
36=cam1 * fs
38=cam2 * fs
40=cam3 * fs
>>>>>>> 920adf625f85240b9410c616f7c7c875f625df30
