[server]
host=localhost

[midi]
# http://www.akaipro.com/products/pad-controllers/lpd-8
device=LPD8
feedback=True

# LPD8 Layout:
#   PAD: (Note events)
#     40, 41, 42, 43
#     36, 37, 38, 39
#   CC: (CC event)
#     5, 6, 8, 9
#     1, 2, 3, 4
#   PC: (prog change event)
#     4, 5, 6, 7
#     0, 1, 2, 3
#   Knobs: (CC event)
#     1, 2, 3, 4
#     5, 6, 7, 8
[eventmap]
40=cam3 cam1 pip
41=cam3 cam2 pip
42=cam3 cam1 sbs
43=cam3 cam2 lec
36=cam1 * fs
37=cam2 * fs
38=cam3 * fs
39=cam1 cam2 sbs
