apiVersion: v1
kind: ConfigMap
metadata:
  name: voctomix-config
data:
  WIDTH: "1920"
  HEIGHT: "1080"
  FRAMERATE: "25"
  AUDIORATE: "48000"
  VOCTOCORE_HOST: "localhost"
  VOCTOCORE_PORT: "9999"
  VOCTOCORE_CLOCK_PORT: "9998"
  TELEMETRY_HTTP_PORT: "8080"
  TELEMETRY_USE_UDP: "1"
  VOCTOMIX_BASE_DIR: "/opt/voctomix"
  SAVE_LOGS: "false"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "voctomix"
  CAM1_PORT: "10000"
  CAM2_PORT: "10001"
  CAM3_PORT: "10002"
  CAM4_PORT: "10003"
  BREAK_PORT: "10004"
  INTRO_PORT: "10005"
  BLANKER_PAUSE_PORT: "17000"
  BLANKER_OFFLINE_PORT: "17001"
  AUDIO_PORT: "18000"
  BG_PORT: "16000"
  BG_IMAGE: "/opt/voctomix/images/backgrounds/bg.png"
  CAM1_SOURCE: "http://cdn.media.ccc.de/congress/31C3-sendezentrum/h264-hd/31c3-sendezentrum-1013-de-Methodisch_inkorrekt_Die_falsche_42_hd.mp4"
  CAM2_SOURCE: "http://cdn.media.ccc.de/congress/31C3-sendezentrum/h264-hd/31c3-sendezentrum-1003-de-Freak_Show_FS147_That_Escalatored_Quickly_hd.mp4"
  CAM3_SOURCE: "http://cdn.media.ccc.de/congress/31C3-sendezentrum/h264-hd/31c3-sendezentrum-1003-de-Freak_Show_FS147_That_Escalatored_Quickly_hd.mp4"
  CAM4_SOURCE: "https://www.w3schools.com/html/mov_bbb.mp4"
  BREAK_VIDEO: "/opt/voctomix/videos/video_cuenta_regresiva_10s.mp4"
  BREAK_AUDIO: "/opt/voctomix/videos/musica_pausa.mp3"
  INTRO_VIDEO: "/opt/voctomix/videos/intro.mp4"
  PAUSE_VIDEO: "/opt/voctomix/videos/SLIDES_video_starting_soon.mp4"
  OFFLINE_VIDEO: "/opt/voctomix/videos/stream_offline.mp4"
  BACKGROUND_MUSIC: "/opt/voctomix/videos/musica_pausa.mp3"
